DictField multipart form field
tapis-project/tapis-ui pull request #155
Opened 2021-09-10 17:31 UTC by jchuahtacc

## Overview:

## Related Github Issues:

- [TUI-1234](https://github.com/tapis-project/tapis-ui/issues/1234)

## Summary of Changes:

## Testing Steps:

1.

## UI Photos:

## Notes:

2021-09-14 21:09 UTC, jarosenb requested changes

2021-09-14 22:09 UTC, jchuahtacc commented on src/tapis-ui/components/jobs/JobLauncher/FieldArray.tsx
> +            remove: () => remove(index),
The component needs to decide whether or not to render the remove button. For example, not all fileInputs are removable if they are "required".

2021-09-15 15:56 UTC, jchuahtacc commented on src/tapis-ui/components/jobs/JobLauncher/FieldArray.tsx
> +  template: any;
default is a reserved keyword. i'll try something else.

2021-09-15 21:09 UTC, jarosenb approved these changes
👍

2021-09-15 21:09 UTC, merged